### ISSUE TITLE
Updates Fat jets module for UL Production

### ISSUE THREAD

**Issue by SiewYan** [mpresill/LatinoAnalysis#2]
## Tracking progress of jets module upgrade for UL Production
- uses CMSSW_10_6_27 for troubleshooting
- UL-Production branch
- all years affected, focuses 17,18 for now
- FatJet, correction, cleaning, systematics modules
- previously in the VBS semileptonic analysis: 

> PUPPI AK8, PT > 200 GeV and |η| < 2.4, softdrop mass required to be between 40 GeV and 250 GeV, cut on N-subjettiness variable τ21 < 0.45 is used to identify jets from W or Z decays, V-jets candidates are excluded if their distance from lepton candidates is ∆R < 0.8, Anti-kT R = 0.4 jets within ∆R < 0.8 from the boosted jet candidates are excluded from the event.
> Corrections:  Correction to Puppi Softdrop mass for V tagging, shifting at the V boson mass peak as a function of pT and η, has been applied as described in [AN-2016/215](https://cms.cern.ch/iCMS/jsp/db_notes/noteInfo.jsp?cmsnoteid=CMS%20AN-2016/215)(Identification and calibration of boosted hadronic W/Z bosons at 13 TeV).
> 

- Sample list for both MC and Data:
  | Year | MC Production | Data Production |
  | ------ | ----- | ------ |
  | 2016 HIPM | [Summer20UL16_106x_nAODv8_HIPM_Full2016v8](https://github.com/mpresill/LatinoAnalysis/blob/UL_production/NanoGardener/python/framework/Productions_cfg.py#L787-L795) | [Run2016_UL2016_nAODv9_HIPM_Full2016v9](https://github.com/mpresill/LatinoAnalysis/blob/UL_production/NanoGardener/python/framework/Productions_cfg.py#L612-L618) |
  | 2016 noHIPM | [Summer20UL16_106x_nAODv8_noHIPM_Full2016v8](https://github.com/mpresill/LatinoAnalysis/blob/UL_production/NanoGardener/python/framework/Productions_cfg.py#L797-L805) | [Run2016_UL2016_nAODv9_noHIPM_Full2016v9](https://github.com/mpresill/LatinoAnalysis/blob/UL_production/NanoGardener/python/framework/Productions_cfg.py#L620-L627) |
  | 2017 | [Summer20UL17_106x_nAODv9_Full2017v9](https://github.com/mpresill/LatinoAnalysis/blob/UL_production/NanoGardener/python/framework/Productions_cfg.py#L808-L816) | [Run2017_UL2017_nAODv9_Full2017v9](https://github.com/mpresill/LatinoAnalysis/blob/UL_production/NanoGardener/python/framework/Productions_cfg.py#L630-L636)|
  | 2018 | [Summer20UL18_106x_nAODv9_Full2018v9](https://github.com/mpresill/LatinoAnalysis/blob/UL_production/NanoGardener/python/framework/Productions_cfg.py#L819-L827) | [Run2018_UL2018_nAODv9_Full2018v9](https://github.com/mpresill/LatinoAnalysis/blob/UL_production/NanoGardener/python/framework/Productions_cfg.py#L638-L645) |
 - JEC  for MC in Run2:
   | Year | Jet-Type | GT | Remark |
   | ------ | ------ | ----- | ------ |
   | 2016 APV | CHS and PUPPI (AK4 and AK8) | [106X_mcRun2_asymptotic_preVFP_v11](https://github.com/cms-jet/JECDatabase/blob/master/tarballs/Summer19UL16APV_V7_MC.tar.gz?raw=true) |  |
   | 2016 noAPV | CHS and PUPPI (AK4 and AK8) | [106X_mcRun2_asymptotic_v17](https://github.com/cms-jet/JECDatabase/blob/master/tarballs/Summer19UL16_V7_MC.tar.gz?raw=true) | |
   | 2017 | AK4PFCHS, AK4PFPuppi | [106X_mc2017_realistic_v8](https://github.com/cms-jet/JECDatabase/blob/master/tarballs/Summer19UL17_V5_MC.tar.gz?raw=true) | JEC based on 106X __Summer19UL17__ (compatible with __Summer20UL17__) |
   | 2018 | CHS and Puppi (AK4 and AK8) | [106X_upgrade2018_realistic_v15_L1v1](https://github.com/cms-jet/JECDatabase/blob/master/tarballs/Summer19UL18_V5_MC.tar.gz?raw=true) | JEC based on 106X __Summer19UL18__ (compatible with __Summer20UL18__)  |
   * https://twiki.cern.ch/twiki/bin/viewauth/CMS/JECDataMC#Recommended_for_MC
   * https://hypernews.cern.ch/HyperNews/CMS/get/JetMET/2131/1.html
 - JEC for data: https://twiki.cern.ch/twiki/bin/viewauth/CMS/JECDataMC#Recommended_for_Data 
 - JR Run2:
   | Year | SF Data | SF MC | Remarks |
   | ------ | ------ | ----- | ------ |
   | 2016 APV | | |
   | 2016 noAPV | | |
   | 2017 | [Summer19UL17_JRV2_DATA](https://github.com/cms-jet/JRDatabase/blob/master/tarballs/Summer19UL17_JRV2_DATA.tar.gz) | [Summer19UL17_JRV2_MC](https://github.com/cms-jet/JRDatabase/blob/master/tarballs/Summer19UL17_JRV2_MC.tar.gz) | they are NOT in a Pt-dependent format, the previously strong pt dependency at high eta is however observed to be reduced in UL |
   | 2018 | [Summer19UL18_JRV2_DATA](https://github.com/cms-jet/JRDatabase/blob/master/tarballs/Summer19UL18_JRV2_DATA.tar.gz?raw=true) | [Summer19UL18_JRV2_MC](https://github.com/cms-jet/JRDatabase/blob/master/tarballs/Summer19UL18_JRV2_MC.tar.gz?raw=true) | they are NOT in a Pt-dependent format, the previously strong pt dependency at high eta is however observed to be reduced in UL |
 
   * https://twiki.cern.ch/twiki/bin/view/CMS/JetResolution#2016_data
 - PUID (AK4 only): https://twiki.cern.ch/twiki/bin/view/CMS/PileupJetIDUL 
 - JetID: https://twiki.cern.ch/twiki/bin/view/CMS/JetID13TeVUL#Recommendations_for_the_13_T_AN1 
> Please note: For AK8 jets, the corresponding (CHS or PUPPI) AK4 jet ID should be used.

 - affected modules MC:
    - Steps:
      - [MCl1loose2017v9](https://github.com/mpresill/LatinoAnalysis/blob/UL_production/NanoGardener/python/framework/Steps_cfg.py#L920-L927)
      - [MCl1loose2018v9](https://github.com/mpresill/LatinoAnalysis/blob/UL_production/NanoGardener/python/framework/Steps_cfg.py#L1028-L1034)

   | Instance | Remarks |
   | ------ | ----- |
   | [leptonMaker](https://github.com/mpresill/LatinoAnalysis/blob/UL_production/NanoGardener/python/framework/Steps_cfg.py#L2749-L2756) |  |
   | [lepSel](https://github.com/mpresill/LatinoAnalysis/blob/UL_production/NanoGardener/python/framework/Steps_cfg.py#L2758-L2765) | |
   | [jetSelUL](https://github.com/mpresill/LatinoAnalysis/blob/UL_production/NanoGardener/python/framework/Steps_cfg.py#L2808-L2816) | | 
   | ~~[CorrFatJetMC](https://github.com/mpresill/LatinoAnalysis/blob/UL_production/NanoGardener/python/framework/Steps_cfg.py#L2855-L2862)~~ | turn off for now, JEC really done centrally |
   | [CleanFatJet](https://github.com/mpresill/LatinoAnalysis/blob/UL_production/NanoGardener/python/framework/Steps_cfg.py#L2865-L2873) | |

- affected modules data:
   - Steps:
      - [DATAl1loose2017v9](https://github.com/mpresill/LatinoAnalysis/blob/UL_production/NanoGardener/python/framework/Steps_cfg.py#L1681-L1687)
      - [DATAl1loose2018v9](https://github.com/mpresill/LatinoAnalysis/blob/UL_production/NanoGardener/python/framework/Steps_cfg.py#L1745-L1751)

  | Instance | Remarks |
  | ------ | ----- |
  | [leptonMaker](https://github.com/mpresill/LatinoAnalysis/blob/UL_production/NanoGardener/python/framework/Steps_cfg.py#L2749-L2756) |  |
  | [lepSel](https://github.com/mpresill/LatinoAnalysis/blob/UL_production/NanoGardener/python/framework/Steps_cfg.py#L2758-L2765) | |
  | [jetSelUL](https://github.com/mpresill/LatinoAnalysis/blob/UL_production/NanoGardener/python/framework/Steps_cfg.py#L2808-L2816) | | 
  | [CorrFatJetData](https://github.com/mpresill/LatinoAnalysis/blob/UL_production/NanoGardener/python/framework/Steps_cfg.py#L2846-L2853) |  |
  | [CleanFatJet](https://github.com/mpresill/LatinoAnalysis/blob/UL_production/NanoGardener/python/framework/Steps_cfg.py#L2865-L2873) | |

### to-do list:
 - [x] troubleshoot Fatjet maker:
   - [x] #4
   - [x] #5
   - [x] #3
   - [x] #8 
   - [x] #6
   - [x] #10
 - [ ] Add more advanced tagging techniques than  W/Z tagging, such as deepAK8 (https://twiki.cern.ch/twiki/bin/view/CMS/DeepAKXTagging) , and respective uncertainties.

Source: [google doc](https://docs.google.com/document/d/1zu6VMU6mDbEqq3a2CVoH_Q0G26YiZYIvjKxpc94KQvw/edit#)

**Comment by SiewYan** [comment]
[FatJetCorrHelper](https://github.com/mpresill/LatinoAnalysis/blob/UL_production/NanoGardener/python/framework/Steps_cfg.py#L2855-L2862)  -> @SiewYan this is not going to be used anymore as embedded in Nanov9, correct 

--> Yes and No. Yes, the doJEC is not needed as it is done centrally [*]; No, we do need it in the future to do uncertainty calculation and jet smearing (JER)

[*] https://github.com/cms-sw/cmssw/blob/CMSSW_10_6_27/PhysicsTools/NanoAOD/python/jets_cff.py#L19-L34

**Comment by SiewYan** [comment]
prepare PR: #237

**Comment by SiewYan** [comment]
Closing this PR. Open a new issue for outstanding.

- [ ] Add more advanced tagging techniques than W/Z tagging, such as deepAK8 (https://twiki.cern.ch/twiki/bin/view/CMS/DeepAKXTagging) , and respective uncertainties.
